[Server]

Guild_Id =  1476692849985851594 #!{here goes your guild ID, must be int} 
            #? Here goes the GI of your development server

[Roles]

Muted = "Muted role" #? Here you change for the 'Mute role' of your server

[Bot]

Prefix = "<"