[Server]

Guild_Id =  1476692849985851594 #!{here goes your guild ID, must be int} 

Log_Channel = 1481157050338906254 #! {here goes your log channel ID, must be int}

[Roles]

Muted = "Muted role" #? Here you change for the 'Mute role' of your server

[Bot]

Prefix = "<"